private["_parameters"];
switch(true)do{
case(isLOPTak):{
_parameters=[
["SIDE",civilian],
["VEHICLES",
    [
    "C_Truck_02_box_F",
    "C_Truck_02_covered_F",
    "C_Truck_02_fuel_F",
    "C_Truck_02_transport_F",
    "LOP_TAK_Civ_Landrover",
    "LOP_TAK_Civ_Offroad",
    "LOP_TAK_Civ_UAZ",
    "LOP_TAK_Civ_UAZ_Open",
    "LOP_TAK_Civ_Ural",
    "LOP_TAK_Civ_Ural_open",
    "RHS_Ural_Open_Civ_01",
    "RHS_Ural_Civ_01",
    "RHS_Ural_Open_Civ_02",
    "RHS_Ural_Civ_02",
    "RHS_Ural_Open_Civ_03",
    "RHS_Ural_Civ_03"
    ]
],
["VEHICLES_COUNT",6],
["MIN_SPAWN_DISTANCE",1000],
["MAX_SPAWN_DISTANCE",1800],
["MIN_SKILL",0],
["MAX_SKILL",0],
["DEBUG",false]];};
default{
_parameters=[
["SIDE",civilian],
["VEHICLES",["C_Offroad_01_F","C_Offroad_01_repair_F","C_Quadbike_01_F","C_Hatchback_01_F","C_Hatchback_01_sport_F","C_SUV_01_F","C_Van_01_transport_F","C_Van_01_box_F","C_Van_01_fuel_F","C_Van_02_transport_F","C_Van_02_service_F","C_Van_02_vehicle_F","I_C_Van_02_transport_F","I_C_Van_02_vehicle_F"]],
["VEHICLES_COUNT",6],
["MIN_SPAWN_DISTANCE",1000],
["MAX_SPAWN_DISTANCE",1800],
["MIN_SKILL",0],
["MAX_SKILL",0],
["DEBUG",false]];};};
_parameters spawn civTraffic_StartTraffic;
